networks:
  staging-network:
    name: staging-network
    driver: bridge

services:

  staging-redis:
    image: redis:7.2
    container_name: staging-redis
    ports:
      - 127.0.0.1:6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 10s
    networks:
      - staging-network

  staging-lanraragi:
    image: staging-lanraragi
    container_name: staging-lanraragi
    ports:
      - 3000:3000
    environment:
      - "LRR_REDIS_ADDRESS=staging-redis:6379"
      - LRR_UID=${MY_UID}
      - LRR_GID=${MY_GID}
    volumes:
      - ./contents:/home/koyomi/lanraragi/content:rw
    depends_on:
      staging-redis:
        condition: service_healthy
    networks:
      - staging-network
