services:

  staging-redis:
    image: redis:7.2
    container_name: staging-redis
    ports:
      - 127.0.0.1:6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 10s

  staging-lanraragi:
    image: staging-lanraragi
    container_name: staging-lanraragi
    ports:
      - 3000:3000
    environment:
      - "LRR_REDIS_ADDRESS=staging-redis:6379"
      - LRR_UID=${MY_UID}
      - LRR_GID=${MY_GID}
    volumes:
      - ./contents:/home/koyomi/lanraragi/content:rw
    depends_on:
      staging-redis:
        condition: service_healthy

  staging-nhdd-db:
    image: pgvector/pgvector:pg17
    shm_size: '1gb'
    container_name: staging-nhdd-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080

  # staging-satellite:
  #   image: staging-satellite
  #   container_name: staging-satellite
  #   command: [ "--host", "0.0.0.0" ]
  #   # user: ${MY_UID}:${MY_GID}
  #   # mem_limit: '4gb'
  #   ports: 
  #     - 8000:8000
  #   environment:
  #     - SATELLITE_DISABLE_API_KEY=true
  #     - LRR_HOST=http://staging-lanraragi:3000
  #     - LRR_API_KEY=lanraragi
  #     - NHDD_DB=postgres
  #     - NHDD_DB_HOST=staging-nhdd-db
  #     - NHDD_DB_USER=postgres
  #     - NHDD_DB_PASS=postgres
  #     - NHDD_DEVICES=cpu
