services:

  redis:
    image: redis:7.2
    container_name: redis
    profiles:
      - lanraragi
    restart: unless-stopped
    ports:
      - 127.0.0.1:6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 10s

  lanraragi:
    image: difegue/lanraragi
    container_name: lanraragi
    profiles:
      - lanraragi
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - "LRR_REDIS_ADDRESS=redis:6379"
      - LRR_UID=${MY_UID}
      - LRR_GID=${MY_GID}
    volumes:
      - ./contents:/home/koyomi/lanraragi/content:rw
    depends_on:
      redis:
        condition: service_healthy

  satellite:
    build: ../
    container_name: satellite
    profiles:
      - satellite
    user: ${MY_UID}:${MY_GID}
    depends_on:
      - lanraragi
    command: [ "--host", "0.0.0.0" ]
    ports:
      - 127.0.0.1:8001:8000 # use 8001; 8000 is reserved for local dev build of satellite.
    environment:
      - LRR_CONTENTS=/home/koyomi/lanraragi/content
      - LRR_HOST=http://lanraragi:3000
      - LRR_API_KEY=lanraragi
      - CATAPULT_HOME=/workdir/catapult
      - SATELLITE_API_KEY=satellite
    volumes:
      - ./contents:/home/koyomi/lanraragi/content:rw
      - ./satellite:/.satellite:rw